
name: amd64-dockerbuild

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "thedrobe" --password-stdin
        docker image build -t thedrobe/traefik-ssl-certificate-exporter:amd64 .
        docker push thedrobe/traefik-ssl-certificate-exporter:amd64
